### ISSUE TITLE
[PG] Price point restriction for billing API

### ISSUE THREAD

**Issue by aravind56060** [vinodtapmobi/havok-operations#100]
Billing API shared with third party client should have price point restriction such that only few price point say for example 10, 15 are open thorough the API, other price point will not work.

**Comment by vinodtapmobi** [comment]
Since the integration with telcos are done by us, we have to make sure only allowed telcos, circles, pricepoints and service goes to billing for each each client.

So we need to have criteria to allow platform admin to configure billing for each client base on the following properties
ClientId, Carrier, Circle, MediaType, PricePoints (CSV), ServiceIds (CSV)
Eg:
TZZ        Airtel      KK            ALL       5,10,15,20,25              ALL
TZZ        Voda      ALL          ALL 

Platform admin can create and edit above details any time.

**Comment by soniyatapmobi** [comment]
This requirement can be done in two part :-1: 

a) Interface for managing the billing configuration.
b) Checking all the billing configuration before billing the user.

For a)
1) We need to create separate table with the following specification in payment gateway
ClientId                not null foreign key reference with client 
Carrier                 not null foreign key reference with Carrier lookup 
Circle                    not null foreign key reference with Circle lookup
MediaType           not null,
PricePoints(csv)   not null
ServiceIds(csv)     can be null

Primary key : ClientId + Carrier + Circle + MediaType

2) An interface for managing the billing configuration under Platform Admin tab by tab name Manage Billing configuration.
3) This interface will have generic gridview which will display all existing billing configurations.
4) Admin can edit and delete the existing billing configuration
5) A button at the top left side for creating the new billing configuration, clicking on which it will redirect the admin to the page where admin can add new billing configuration.
6) Add billing configuration page will have following control
a) Drop down of existing clients
b) Drop down of Carrier
c) Drop down of Circle
d) Drop down of Media type
e) Text box for comma separate price points.
f) Text box for comma separate services id's.
g) Submit button.

**Comment by soniyatapmobi** [comment]
For b)

1) We will add new class by name ProcessBilling inside which will have function whose signature is as follows
public bool Proceed(string clientid, string carrier, string circle, string mediatype, string pricepoint)

2) This function will check all existing billing configuration for the requesting client. If pricepoint requested is not matching with any of the billing configuration, then it will return false else return true.

3) This function will be called in event.aspx page.When true, normal flow will proceed else it will show to the user invalid price point

**Comment by aravind56060** [comment]
Test Results:
   1) While creating billing config pricepoints text box accepts alphabets and special characters also.
   2) Created Date Filter is throwing error regardless any values entered in it.
   Other functionalities are working fine.

**Comment by soniyatapmobi** [comment]
Both the above issues are solved
