### ISSUE TITLE
[PL] Airtel billing not working while live testing

### ISSUE THREAD

**Issue by saurabhtz** [vinodtapmobi/havok-operations#109]
Airtel billing is not working while doing live testing of the URL .
Have created billing of Airtel.

**Comment by soniyatapmobi** [comment]
Please provide me the msisdn u tested with ?

**Comment by soniyatapmobi** [comment]
Please define the ppd charging for airtel for delhi circle. There is no charging define for delhi airtel

**Comment by saurabhtz** [comment]
Closed
