### ISSUE TITLE
[PL] - Campaign tagging for links

### ISSUE THREAD

**Issue by vinodtapmobi** [vinodtapmobi/havok-operations#12]
Client should be able to attach campaign tags to links to track promotions done through different partners/channels.

The querystring will follow standard UTM parameters.
http://blog.kissmetrics.com/how-to-use-utm-parameters/

**Comment by soniyatapmobi** [comment]
1) As discussed with satheesh, they dont want any campaign tagging in the URL. Instead they want a feature to define the promotion type like ( sms, live, third party) at time of creating new page.

2) It will be more easily for them to track the revenue for different promotion type.

**Comment by vinodtapmobi** [comment]
We are going with UTM source. Report can be grouped using utm source.
The available parameters are 
- utm_source
- utm_medium
- utm_campaign
- utm_content

We will create a page in portal to fill all these values and system will generate the url.

**Comment by vinodtapmobi** [comment]
https://support.google.com/analytics/answer/1033867?hl=en

**Comment by soniyatapmobi** [comment]
The interface for generating URL is working fine.
