### ISSUE TITLE
[PL] - Click to enter feature

### ISSUE THREAD

**Issue by vinodtapmobi** [vinodtapmobi/havok-operations#14]
Client should be able to configure click to enter restrictions based on 
1. Carrier
2. Circle
3. Time of day
4.Start Date and End Date

**Comment by soniyatapmobi** [comment]
1) It has to be implemented based on page id or based on promotion type , need to be discuss.

**Comment by vinodtapmobi** [comment]
The url parameter will be c2e=1.

**Comment by soniyatapmobi** [comment]
1) For creating click to enter add c2e=1 to the download link.
2) Once the request comes to the download handler we check whether request contain c2e parameter or not
3) If c2e parameter is not present normal flow will go
4) Else we will check the click to enter configuration for the request carrier, circle, date and time.
5) If any click to enter configuration matches and is enabled then user will be billed else it will be redirected to the r.aspx of the requesting page id

**Comment by robintapmobi** [comment]
What if there are 5 link in a particular carrier at any particular circle with different time zone for click to enter???

Banner Click to enter 0600-0800
Text Link click to enter 0900-1200
Pack click to enter 1300-1500....

**Comment by soniyatapmobi** [comment]
Added the functionality to configured the links also for click to enter.
