### ISSUE TITLE
Not able to download the banner on Platform Node through web browser 

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#148]
Expected:Should be able to download the banner.

Steps:
1.Add banner and Save it at the editor screen 
2. On platform Node--> Click on the Banner -->
Actual: Not able to download the banner.

Note: Mozilla Firefox-30 is the web browser used.

Tested URL at the platform node: http://r.tapmobi.in/r.aspx?pageid=282#

Below is the screenshot:
![banner not downloading](https://cloud.githubusercontent.com/assets/8113291/3609195/91dfa2d4-0d74-11e4-9886-85e15f8db554.png)

**Comment by aravind56060** [comment]
We cannot download any banners. They are used only for redirecting to some other page
