### ISSUE TITLE
[PL] - Templating feature

### ISSUE THREAD

**Issue by vinodtapmobi** [vinodtapmobi/havok-operations#16]
{charging}
{meta}
{profile}
{control}
etc.

**Comment by aravind56060** [comment]
Template controls had the following options till now.
- bullet                       {bullet:<imgaeId>}
- badge                        {badge:<imageId>}
- link                         {link:text=<text>|url=<url>}

Client should have option to display the following information using Template controls
1. Metadata -  {meta:<property>}
2. Device Info - {device:<property>}
3. Network detail - {network:<property>}
4. Request detail - {request:<property>}
5. Site detail - {site:<property>}
6. Page detail - {page:<property>}

**Comment by aravind56060** [comment]
Following properties can be used in template Text
1) network - carrier,circle,msisdn,balance,balanceunit
2) device -
    \* make,
    \* model,
    \* width,
    \* height,
    \* maximagewidth,
    \* maximageheight,
    \* iswirelessdevice,
    \* istablet,
    \* nokiaseries,
    \* os,
    \* osversion,
    \* browser,
    \* preferredrenderingtype,
    \* supportsviewportmetatag,
    \* supportshtml5canvas,
    \* supportsjavascript,
    \* supportsgifimage,
    \* supportspngimage,
    \* supportsjpgimage,
    \* supportsbmpimage,
    \* prefferedimageformat,
    \* supportmp3,
    \* supportmp4,
    \* supports3gpp,
    \* maxdatarateinkilobits,
    \* supportswifi,
    \* supportsvpn,
    \* maxurllengthinrequests,
    \* supportsomadownload,
    \* supportsringtonedownload,
    \* supportswallpaperdownload,
    \* wallpapermaxwidth,
    \* wallpapermaxheight,
    \* supportsprogressivedownload,
    \* supportsvideostreaming,
    \* supportswappush,
    \* supportsj2me,
    \* supportscookie
3) page - name
4) site - name, allowedcircles, allowedcarriers
5) meta - 
    \* contentid
        \* title
        \* clientid
        \* musiclabel
        \* contenttype
        \* category
        \* subcategory
        \* genre
        \* language
        \* album
        \* musicdirector
        \* lyricist
        \* cast
        \* director
        \* producer
        \* singers
        \* productionhouse
    \* priority
