### ISSUE TITLE
[PL] - Designer Content Block - Infermode customizations

### ISSUE THREAD

**Issue by vinodtapmobi** [vinodtapmobi/havok-operations#2]
In infermode, currently only the blocks other than the current blocks are getting hidden. Client should be able to select which rows gets shown or hidden.

Solution1: For each control, have a property called ShowInInferMode. Based on which the row is displayed or hidden.

Solution2: Create Id property for all controls. And user can enter which ids to show. Based on this, on the page, only given rows with matching ids are shown.

Solution3: Create Infermode control. Which ever page having infermode control can render a block control in one of its rows.

**Comment by aravind56060** [comment]
Normal infer mode has been implemented. 
In this mode all block controls other than the one in infer mode are hidden.

## Implemention

1) When a control enters into Infer mode, we will add 'IM' parameter in query string and pass the control index as its value.
2) While rendering the page if query string has IM parameter, then check the whether to render the control based on Control group and infer mode control index.
