### ISSUE TITLE
[CG] - Content format conversion tool

### ISSUE THREAD

**Issue by vinodtapmobi** [vinodtapmobi/havok-operations#20]
We need to create a tool which will convet techzone exisitng content fomat into our new content formar.

**Comment by aravind56060** [comment]
Techzone existing content are in the following folder structure
 1) Animation
-  50x50
-  360x480
-  800x1280
- Metadata.xls

2) Wallpaper
-  50x50
-  360x480
-  800x1280
-  Metadata.xls

3) Videos
-  3gp
-  Mp4
-  Thumbnails
-  Metadata.xls

4) Fulltrack
-  AMR
-  Full
-  MP3
-  Metadata.xls

## Implementation

1) Converted content will be available in Output folder.
2) Parse the metadata and for each content in the metadata file create a folder.
3) Copy all the files for the same content into single folder and create metadata.xml inside that folder.
4) File and metadata are mapped based on the code(Ccode,Vcode etc) provided in the metadata.

**Comment by saurabhtz** [comment]
Will it create a separate XML files from a single xlsx file and copy it in respective folders?

**Comment by aravind56060** [comment]
Yes. Separate xml files are created from single Excel file.
