### ISSUE TITLE
[CG] - Content Gateway Cron throwing exception for max key length

### ISSUE THREAD

**Issue by soniyatapmobi** [vinodtapmobi/havok-operations#21]
While running the content gateway cron it throwing exception as specified key was too long max key length is 767 bytes 

My sql error no 1071

**Comment by vinodtapmobi** [comment]
Aravind, are you geting the same?

**Comment by vinodtapmobi** [comment]
@soniyatapmobi Mention the details of the solution also for future reference.

**Comment by soniyatapmobi** [comment]
This error was coming only at the time of creating the database for the first time. 

File path ContentGateway\ContentGateway.Core\Data\DbContexts\EntityFramework\Initializers\MySql\MySqlDatabaseInitializer.cs at line 26 throwing the error as "Specified key was too long; max key length is 767 bytes"

This error tells that primary key can not take more than 767 bytes of data for any of the table in the database.

Now whenever we getting this error we are throwing it by checking the error.Number in the catch block.

This number may change with the different version of entity frame work. For the current version this number is 1071.
