### ISSUE TITLE
[CG] - Unable to add content in to Set

### ISSUE THREAD

**Issue by SatheeshAnandan** [vinodtapmobi/havok-operations#27]
After creating the New Set unable to add the selected content event after clicking on " Add Checked Items"

**Comment by aravind56060** [comment]
We are able to add items to set. The issue was once the items are added it is not refreshing the search items below. So if you try adding existing content again, it won't add. Now we are refreshing the search contents once added and existing contents are not displayed in SetAddItems.aspx.
