### ISSUE TITLE
[PL] - Search sites/pages feature

### ISSUE THREAD

**Issue by vinodtapmobi** [vinodtapmobi/havok-operations#3]
For Sites: User must be able to search for a particular site based on
1. Site Name
2. Site No

For Pages: User must be able to search for a particular page based on
1. Page Name
2. Page No

**Comment by SatheeshAnandan** [comment]
![create page option](https://f.cloud.github.com/assets/6543194/2060396/64a060fa-8c15-11e3-811d-f78cf0058d1a.PNG)
Create Page option is removed… (earlier it was available)

Regards

Satheesh Anandan

**Comment by SatheeshAnandan** [comment]
Now unable to design page getting below 

![image](https://f.cloud.github.com/assets/6543194/2060420/f49579ce-8c16-11e3-8ea6-cc677c7d87b9.png)

**Comment by vinodtapmobi** [comment]
A generic filter panel is included for all grid-views wherever necessary. You can now filter sites and pages.

**Comment by vinodtapmobi** [comment]
Filter panel "Reset" button has been added. Click reset will reset the filters.
