### ISSUE TITLE
[PL] Tab Function is not working.

### ISSUE THREAD

**Issue by saurabhtz** [vinodtapmobi/havok-operations#38]
Trying to enter links and Text but its not reflecting the same on the page any where.

**Comment by aravind56060** [comment]
Tab is working fine. You should not enter link for tab control. We need to enter the text and the number of controls to be tagged for that tab in sequential order. Say for example if you have 4 controls in a page and you have 2 tabs. Incase if you want to add only the first control of the page in tab A you need to mention tab text and 1. And for the other 3 controls in second tab. 'tab text' and 3.
