### ISSUE TITLE
[PL] - Add duration/validity time for PPD in Charging Specification

### ISSUE THREAD

**Issue by vinodtapmobi** [vinodtapmobi/havok-operations#4]
Client should be able to configure the duration/validate time for PPD in charging specification. So, if a user is charged for a PPD content, he should not be charged again until the validity time expires. So, he can download the **same content** multiple times.

Based on discussion with Sateesh, Kamlesh, Ruchika, Neha:

Rules:
1. The duration/validity MUST be **based on ContentID**. So that if same content is clicked in another page, the user must not be charged again.
2. This must be restricted to pages of a single site. If user clicks on the same content on different site, he **MUST** be charged.

**Comment by soniyatapmobi** [comment]
1) Add the validity duration time for ppd charging.
2) Check in download logs if user has being billed for that content id with in that duration.
3) If User is exiting user we need to give direct download, otherwise will redirect him to payment gateway for billing.

**Comment by soniyatapmobi** [comment]
This is implemented based on the msisdn, contentid, siteid and applied charging id for the current time.
