### ISSUE TITLE
P1 issue:HUD Carousel type(Next arrow and Previous arrow buttons) functionality not working for any content at platform node for lumata

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#403]
Tested URL: http://l1.tapmobi.in/r.aspx?pageid=255

Expected: When user clicks on Next arrow, it should be redirected to the next image page accordingly and on Prev arrow, it should redirect to previous page.

Actual: When user clicks on next arrow >, its redirecting to the third page and when user is on the last page and clicks on previous arrow >, its redirecting to the second page.

Below is the screenshot for Wallpapers and Video content :

![image](https://cloud.githubusercontent.com/assets/8113291/4315725/7c2cbae0-3efb-11e4-8ec2-25b0e9547d19.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Now Previous and Next buttons for HUD carousel type is working fine as expected.

Tested URL: http://l1.tapmobi.in/r.aspx?pageid=475

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4913379/4826be64-64b0-11e4-878e-c9bd6f2e0a4c.png)
