### ISSUE TITLE
Images of the Wallpaper type not displaying when set to 55% display on editor page at New UI platform

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#409]
Expected: Should display the image accordingly.

Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=66

Precondition: User is on editor page and Selected Image control at Slots screen

Tested ImageID: CDEMWAL20140826161316072
Steps:
1. Select Image by clicking ImageID button  on Properties screen
2. Click on Search button and click on the image (Wallpaper type) and click on Save button
3. Set Image percentage =55 on Properties screen and Click on Save button.

Actual: The selected image not displaying.

Note: This issue is common across all wallpaper images

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4454357/7fc29716-486e-11e4-91f7-6194abcfee53.png)

**Comment by binittapmobi** [comment]
content gateway was not able to render images of all sizes, is fixed now

**Comment by virupaksh** [comment]
Retested reported issue and issue has been fixed, hence closing the same.

Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=66

Below is the screenshot for the image at 55%

![image](https://cloud.githubusercontent.com/assets/8113291/4558461/9a0b0860-4ee0-11e4-8a51-532dde6a931e.png)

Below is the screenshot for the image at 70%
![image](https://cloud.githubusercontent.com/assets/8113291/4558484/d93ba292-4ee0-11e4-83c3-2aaf2393062c.png)
