### ISSUE TITLE
P2 issue: Allowed Carriers and Circle field on Properties screen at editor is displaying as " 1 item(s) selected when there are no items selected at New UI platform

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#411]
Expected: Should display as "0 items selected", when there are no items(s) selected.

Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=66

Precondition: User has added footer control (Basic -->Footer)
Steps to Reproduce:
1.  Click on Allowed Circles And Carriers button on Footer properties screen, Matrix Selection Dialog box pops up.
2. Deselect all fields and click on OK button and click on Save button

Actual:1 item(s) selected 

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4455395/bac7e40a-487e-11e4-94ab-f7f443c647f5.png)

**Comment by binittapmobi** [comment]
fixed

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4459334/3f7899c6-48aa-11e4-8deb-8d8c9df0f5fb.png)
