### ISSUE TITLE
P2 issue: Master checkbox functionality not working on Matrix Selection screen for Allowed carriers and Circles fieldon properties screen at editor on New UI platform portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#412]
Expected: Master checkbox functionality should work as expected.

Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=66

Precondition: User has added Footer control

Steps:
1. Click on Allowed Carriers and Circle button on Footer Properties screen 

Actual: All the items displaying as checked, where as Master check-box displaying as unchecked.

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4455581/dbad12ec-4880-11e4-9d51-07201e32064a.png)

**Comment by binittapmobi** [comment]
fixed

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4459375/84ea6444-48aa-11e4-9d98-c04f8679bb94.png)
