### ISSUE TITLE
P2 issue: Render Item Template As Link functionality for Wallpapers is not working at New UI platform portal(editor)

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#414]
Expected: When user sets the value as "True" for Render Item Template As Link, The item template should behave as link.

Tested URL: http://p1.tapmobi.in/App/Gui/Editor.html?pageId=255

Precondition: User is in Editor page and Added Wallpaper control

Show Item Title drop-down  as "True" in properties screen for wallpaper
Render Item Template As Link as "True" in properties screen for wallpaper

Steps:
1. Enter Item template text as " Item" and Click on Save button on Wallpapers- properties screen
2. Click on Item Title style button on Properties screen and Set the value as "Underline" for Link Decoration drop-down in Style dialog and Click on OK button and Click on Save button.
3. Entered text is displayed in the title as underline on slots screen, Set the value as "False" for Render Item Template as Link drop-down.

Actual: Item title along with template displaying as Link
Expected: Item title along with template should not display as Link.

Below is the screenshot for Wallpapers control:
![image](https://cloud.githubusercontent.com/assets/8113291/4471058/513208bc-4933-11e4-8733-7b725f554627.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/app/gui/editor.html?pageId=401

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4699679/2690c98e-5844-11e4-85e5-61fd175a2df8.png)
