### ISSUE TITLE
P2 issue: Select All Master check-box not displaying as checked, when all the items under it are checked on New UI platform portal/editor

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#415]
Expected: When user selects all the items present under Select All checkbox, by default Select All should display as checked.

Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=66

Below is the screenshot on Editor for all controls:
![image](https://cloud.githubusercontent.com/assets/8113291/4471351/6692656c-4938-11e4-8027-9033f2fdb48d.png)

Step:
1. Presentation -->View Sites -->Click on Edit button -->Observe the Select All master box on Edit Site page as below
Note: This issue is common across all pages such as: Edit Users/Edit Groups page.
![image](https://cloud.githubusercontent.com/assets/8113291/4471384/e4de8932-4938-11e4-8f3c-5fb53fbdde8d.png)

**Comment by binittapmobi** [comment]
default selection added at page load

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested url: http://192.168.0.62:90/

Below is the screenshot across different pages:

Edit sites page:

![image](https://cloud.githubusercontent.com/assets/8113291/4523999/8188df90-4d3e-11e4-9a9b-402a72ed8ef3.png)

Editor page:

![image](https://cloud.githubusercontent.com/assets/8113291/4524028/c22d1ec6-4d3e-11e4-8b5a-ea610a9ed86c.png)
