### ISSUE TITLE
P2 issue:The request is invalid error message popping up in dialog and we are able to drag it on entering the empty input (Without pageid) on editor page at NewUI editor

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#416]
Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=

Steps:
1. Enter the url as " http://192.168.0.62:90/app/gui/editor.html?pageId=  on editor page

Actual: The request is invalid dialog popping up and it can be dragged and dropped anywhere across the page.

Expected: Error message stating "The request is invalid" should be displayed without any pop up.

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4471542/75f88218-493b-11e4-9072-759e8d9af50a.png)

Note: On entering the unavailable page-id, The error message should display stating "Requested Page is not available".

**Comment by binittapmobi** [comment]
done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closed. Below is the screenshot:
Tested URL's: http://192.168.0.62:90/app/gui/editor.html?pageId=
                       http://p2.tapmobi.in/app/gui/editor.html?pageId=

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4556709/3a0a946c-4ecc-11e4-8c8e-26d1fe80f022.png)
