### ISSUE TITLE
P3 issue: Columns like SetID, Setname, No.of items, Commands and Images missing on Select Content Set window on editor at NEWUI portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#419]
Expected: Columns display like SetID, Setname, No.of items, Commands and Images make user easy to identify with.

Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=66

Precondition: User has added Wallpaper content

Steps:
1. Click on Set ID button under Content on Properties screen 
2. Click on Search button in Select content Set dialog

Actual: No column fields displaying as below in the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4474243/58178eca-495d-11e4-8691-463a2812b883.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same

Tested URL: http://p2.tapmobi.in/app/gui/editor.html?pageId=401

Note: Issue has been fixed for all controls

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4658979/aed1dd10-5506-11e4-9395-c5bd5e99169a.png)
