### ISSUE TITLE
[PL] In Image tab need to define image size on my onn instead of %.

### ISSUE THREAD

**Issue by saurabhtz** [vinodtapmobi/havok-operations#42]
I want to have the right to define width and Height of the Image in the Image tab instead of %.

Right & left alignmet of image is not working.
Text alignment is not working.
Text i cant write in multiple rows. how can i break the line when needed?
Multiple text links in front of a single image & image will be having different link.
ref:- M.hungama.com   at the bottom of the page.

**Comment by vinodtapmobi** [comment]
All images are based on % so that it adapts properly for the device. So we will not have any fixed size images  in this platform.
