### ISSUE TITLE
P2 issue:  Image(Any content-type) is not displaying for source type as "Consent Preview" at editor on NewUI platform

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#420]
Expected: Consent Preview image should display on selecting Consent Preview as the source.

Tested URL: http://p2.tapmobi.in/app/gui/editor.html?pageId=373

Note: Image is not displaying for any precentage display when user selects the source type as " Consent Preview"

Precondition: User is in editor page and added Image control at Slots screen

Steps:
1. Select Display type as "Imageonly or " ImageAndTemplate" on Properties screen
2. Select Source as "Consent Preview" on properties screen
3. Select any image (for any content) from ImageID button and save it

Actual: Selected image is not displaying at Slots screen/Preview page for any resolutions as below in the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4523572/2a233a0c-4d39-11e4-89f1-548606c2f620.png)

**Comment by binittapmobi** [comment]
blank image added

**Comment by virupaksh** [comment]
Fixed on Local URL, need to publish the same in P2.tapmobi.in, hence closing the same. After publishing, will check in p2.tapmobi.in, hence closing the same . 

Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=66

Below is the screenshot for the same:
![image](https://cloud.githubusercontent.com/assets/8113291/4558249/a2542e14-4edd-11e4-8d54-4c3d97cbc8c1.png)

**Comment by virupaksh** [comment]
Fixed on Local URL, but open on P2.tapmobi.in

Tested URL:  http://p2.tapmobi.in/app/gui/editor.html?pageId=373

Below is the screenshot at P2 editor

![image](https://cloud.githubusercontent.com/assets/8113291/4592257/3014bfce-5079-11e4-9d28-9b537fb544d1.png)

**Comment by binittapmobi** [comment]
Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/app/gui/editor.html?pageId=401

Below is the screenshot for the same.

![image](https://cloud.githubusercontent.com/assets/8113291/4697385/24b42152-5825-11e4-8eed-17aab542a39e.png)
