### ISSUE TITLE
P2 issue: Alignment of Page number display is not proper at the footer of the Select Image dialog box at editor on New UI platform portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#421]
Expected: There should be consistent page number display across all pages and alignment should be same across all pages

Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=66

Note: This issue exist across all screens where there are more than 10 pages in it.

Precondition: User is in editor page and added Image control at slots screen.

Display type is Image only
Source is SetID or ImageID

Steps:
1. Click on ImageID button on Image -Properties screen
2. Select Image dialog box and Select the Media type as Videos and Click on Search button
3. Click on Page Number 9 at the footer and Click on Next button.

Actual: Display for Page number 10 on wards varying as below

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4526159/b047fd02-4d5c-11e4-9b39-41d87ee99fa8.png)

**Comment by binittapmobi** [comment]
fixed

**Comment by virupaksh** [comment]
Retested the reported fixed issue and issue has been fixed, hence closing the same.

Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=65

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4537899/f33e8976-4de5-11e4-97c3-23f228063fac.png)

**Comment by virupaksh** [comment]
Tested URL: http://p2.tapmobi.in/app/gui/editor.html?pageId=373

Reopening the issue as below in the screenshot

![image](https://cloud.githubusercontent.com/assets/8113291/4591049/305ec716-5067-11e4-8d1a-eec2d6856d02.png)

**Comment by binittapmobi** [comment]
done

**Comment by virupaksh** [comment]
Retested the reported fixed issue and issue has been fixed, hence closing the same.

Tested URL:  http://p2.tapmobi.in/app/gui/editor.html?pageId=363

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4611928/748d5ff0-52c0-11e4-9299-38daed6a019f.png)

**Comment by virupaksh** [comment]
Retested the reported issue and Alignment of Next button is not proper as well as display of all buttons at footer of the screen is also not proper as below in the screenshot:

Note: This issue is common across all screens in editor page

![image](https://cloud.githubusercontent.com/assets/8113291/4804505/687454cc-5e6d-11e4-99dd-c36246a47413.png)

**Comment by binittapmobi** [comment]
Done

**Comment by virupaksh** [comment]
Fixed, hence closed.

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4975916/79acc750-6904-11e4-96f4-3aa2007d967c.png)
