### ISSUE TITLE
P1 issue: An error has occurred dialog popping up, when user clicks on Last button on Select Image window at editor on Lumata platform portal 

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#422]
Expected: When user clicks on Last Button, Last page consists of images should display.

Tested URL: http://p1.tapmobi.in/App/Gui/Editor.html?pageId=373

Precondition: User is in editor page and added image control

Steps:
1. Click on ImageID button, Select Media type as Video and Click on search button on Select Image window
2. Click on Last button

Actual: An error has occurred error message dialog popping up as below in the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4537380/fe4ab840-4dda-11e4-9490-9e3084494905.png)

**Comment by binittapmobi** [comment]
fixed

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/app/gui/editor.html?pageId=373

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4557262/93ed9f1a-4ed1-11e4-9942-b87b0d22f20b.png)
