### ISSUE TITLE
P2 issue: "All" type value is missing in the Media type drop-down present on the Select Image window at editor on NewUI platform

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#423]
Expected: "All" value should display to make it user friendly.

Tested URL: p.tapmobi.in/App/Gui/Editor.html?pageId=373

Actual: No value (Empty type) present in the drop-down as below in the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4537733/5d6969f0-4de2-11e4-9f46-1b1f092792b3.png)

**Comment by binittapmobi** [comment]
removed

**Comment by virupaksh** [comment]
Add the Value as "All" in the drop-down-list present in the Select Image dialog on editor

**Comment by binittapmobi** [comment]
added

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=66
http://p2.tapmobi.in/app/gui/editor.html?pageId=373

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4556888/f4c0a0e8-4ecd-11e4-9b1d-a2e5bf9cb6c7.png)
