### ISSUE TITLE
P4 issue: No message is displayed to the user, when there are no item(s) available for the corresponding content type like Wallpapers, Animation, Apps , Songs etc.. on Select Image window at editor on NewUI platform

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#424]
Expected: Should display the message as " No item(s) available"

Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=65

Precondition: User is in editor page and added image control.
Display type as "ImageOnly/ImageAndTemplate"
Source as "ImageID"

Steps:
1. Click on ImageID button and Select Animation/Apps as the Media Type and click on Search button

Actual: No message is displayed to the user

Expected: " No item(s) available" message should be displayed to the user.

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4538247/4ca0f6f6-4dec-11e4-851b-558334fb61a7.png)

**Comment by binittapmobi** [comment]
mesage added

**Comment by virupaksh** [comment]
Message added at Select Image window.

Same message can be added at Select Content Set window for all contents such as Games, Apps, Animation, Wallpapers etc... as below.
Below is the screenshot for Games content (No items available for Games) 

![image](https://cloud.githubusercontent.com/assets/8113291/4555386/e77ecf1a-4ebc-11e4-850c-25f6a6be4f85.png)

**Comment by binittapmobi** [comment]
Done

**Comment by virupaksh** [comment]
No message has been added as below in the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4975877/fe08ffc4-6903-11e4-99b7-cabd6ea1b04b.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed for SetID types as well, hence closing the same.

Tested URL:http://p2.tapmobi.in/app/gui/editor.html?pageId=529

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/5142519/8364cc90-71a9-11e4-83ec-bdcc7ae82146.png)
