### ISSUE TITLE
P1 issue: Oops something went wrong error message is displayed on clicking Next button (page number) at content-set page on NewUI platform after clicking on Edit link for the SetID on Select Content Set window at editor

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#425]
Expected: On clicking corresponding page number, corresponding page should display 

Tested URL at Content-set page: http://192.168.0.62:90/ContentSet/Items?id=44

Tested URL at editor page: http://192.168.0.62:90/app/gui/editor.html?pageId=65

Precondition: User is on editor page and added wallpaper content

Note: This issue exist across all contents 

Tested Set ID= 44

Steps:
1. Click on Set ID button on properties screen for wallpaper.
2. Click on Search button on Select Content-set window, Click on Next button at the footer of the Select Content-set window.
3. Click on Edit link of SetId=44, system redirects the user to the Content set items page
4. Click on Next button at Content setitems page

Below is the error throwing at url: http://192.168.0.62:90/html/Error.html?aspxerrorpath=/ContentSet/44
Oops. Something went wrong or page not found. Please go back and try again.

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4540331/953f4736-4e06-11e4-8aaf-2a63d3a2df79.png)

**Comment by binittapmobi** [comment]
fixed

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://192.168.0.62:90/ContentSet/Items/4?grid-page=1&grid-page-size=12&grid-column=Priority&grid-dir=1
