### ISSUE TITLE
P1 issue: ContentID is field missing on Downloads page at New UI platform (p2.tapmobi.in)

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#429]
Expected: Content-ID field should be present on Downloads so that user will get to know which content they downloaded.

Tested URL: http://p2.tapmobi.in/Downloads

Below is the screenshot of the Downloads fields where ContentID field (Column) is missing :

![image](https://cloud.githubusercontent.com/assets/8113291/4554118/a8d18fe2-4ea7-11e4-9bad-d1dc5aa64c54.png)

Below is the screenshot where ContentID field is missing in the Details dialog
![image](https://cloud.githubusercontent.com/assets/8113291/4554123/c17b17ca-4ea7-11e4-993b-64c1ba138fdb.png)

**Comment by binittapmobi** [comment]
added

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/Downloads

Below is the screenshot for the same:

![image](https://cloud.githubusercontent.com/assets/8113291/4557040/82a733d0-4ecf-11e4-9f92-76daa1eb3078.png)
