### ISSUE TITLE
P1 issue: Pack charging specifications displaying in Select Subscription charging dialog at editor on New UI platform

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#431]
Expected: Only Subscription charging specifications created should be displayed in Select Subscription Charging dialog.

Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=63

Note: This issue is applicable for all content types.

Precondition: User is in editor page and added wallpaper content

Steps:
1. Click on Subscription Charging ID button
2. Click on Search button in Select Subscription Charging dialog
3. Click on Next button at the footer of the Select Subscription charging dialog

Actual: Observe the List of Pack charging created specifications in Select Subcription Charging dialog as below in the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4556619/4f408856-4ecb-11e4-8647-207f14f6dd55.png)

**Comment by binittapmobi** [comment]
fixed

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://192.168.0.62:90/app/gui/editor.html?pageId=66

Below is the screenshot for Songs control:

![image](https://cloud.githubusercontent.com/assets/8113291/4559040/942726d4-4ee7-11e4-9866-fad518e6397c.png)
