### ISSUE TITLE
P2 issue: No message is displayed to the user when the page is not published at platform node (published property= unchecked) at P2.tapmobi.in

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#432]
Expected:Message stating "Requested page is not available at this point in time. Please try later " should be displayed at platform node.

Actual: No message (Empty) is displayed to the user at platform node

Tested URL at node: http://l1.tapmobi.in/r.aspx?pageid=373

Step:
1. User enters the url as "  http://l1.tapmobi.in/r.aspx?pageid=373"

Below is the screenshot of the page at platform node:
![image](https://cloud.githubusercontent.com/assets/8113291/4557396/323d3bd4-4ed3-11e4-8261-fecd5d9ede77.png)

**Comment by binittapmobi** [comment]
message added

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.
