### ISSUE TITLE
P1 issue: No message is displayed to the user, when user enters the design page with the unavailable page ID at editor on NewUI platform

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#433]
Expected: Should display the message stating "Requested page is not available"

Tested URL at editor: http://p2.tapmobi.in/app/gui/editor.html?pageId=374
                                  http://192.168.0.62:90/app/gui/editor.html?pageId=99

Note: PageID =374/99 is not available

Precondition: User is in editor page of 373

Steps:
1. Enter the url as "http://p2.tapmobi.in/app/gui/editor.html?pageId=374" on editor 

Note:User is able to create and save the page which is not available by adding controls on it.

Actual: No message is displayed as below in the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4558133/d2d65c12-4edb-11e4-94f3-f90e1dda45c7.png)

**Comment by binittapmobi** [comment]
done

**Comment by virupaksh** [comment]
Tested URL: http://p2.tapmobi.in/app/gui/editor.html?pageId=363

Message added in the pop-up, Instead add the message text  (No need to add in the dialog)

Below is the screenshot for the pop up:

![image](https://cloud.githubusercontent.com/assets/8113291/4624970/aa9a15ee-536e-11e4-8b21-4a47b94828c7.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/app/gui/editor.html?pageId=444

![image](https://cloud.githubusercontent.com/assets/8113291/4662905/b0a579dc-5536-11e4-8de7-8dd8e78029e1.png)
