### ISSUE TITLE
P3 issue: Created By field is displaying as null and Id field on Pack Subscribers not sorted by descending order by default on Pack Subscribers page at NewUI portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#434]
Expected: By default Id field on Pack Subscribers should be sorted by descending order  and Created By field can be removed from displaying.

Tested URL:http://p2.tapmobi.in/Subscribers

Steps:
1. Subscribers -->View Pack Subscribers

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4559456/664a736a-4eec-11e4-86ae-3f58fd771c7e.png)

**Comment by binittapmobi** [comment]
done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/Subscribers

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4678112/4049e9fa-55f1-11e4-981c-cce55b52fc5c.png)
