### ISSUE TITLE
P2 issue: Same ContentID is displaying for all carriers and circles for Content Name as "Pack" in Gateway Transaction/Charging page logs at PGPL

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#435]
Expected: ContentID  should be specific wrt the content downloaded by the user each time. 

Tested URL: http://pgpl.tapmobi.in/App/Gateway/Transaction.aspx
                    http://pgpl.tapmobi.in/App/Charging/Aircel.aspx

Below is the screenshot for the same:
![image](https://cloud.githubusercontent.com/assets/8113291/4559689/780fade8-4eee-11e4-9523-a11184fd439a.png)

**Comment by soniyatapmobi** [comment]
For pack control we are sending one constant content id to the billing API.
That's why its showing same content id for the pack
