### ISSUE TITLE
P1 issue: Custom Reports functionality not working at p2.tapmobi.in

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#436]
Expected: On entering valid data and clicking on Generate Button, the corresponding data should be displayed in the form of chart/graph.

Tested URL: http://p2.tapmobi.in/CustomReports

![image](https://cloud.githubusercontent.com/assets/8113291/4560053/fcbfd696-4ef1-11e4-95ff-d5c63cdabf4b.png)

**Comment by binittapmobi** [comment]
Done

**Comment by virupaksh** [comment]
Retested the reported issue, error message has been fixed.

Tested URL: http://p2.tapmobi.in/CustomReports

Below are the scenarios which needs to be addressed.
1. Select Report type as Visitor Report , Display as charts = Selected, Select any Start and End Date, Select any carrier and circle ex (Airtel -Karnataka)

Expected: Chart should display only on selected carrier and circle i.e (Aircel -Karnataka)

Actual: Chart is displaying for all carriers and circles as below in the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4701646/2ec1ba2a-585b-11e4-8ff5-6d1fc2034468.png)
1. When there are no downloads  (Download count=0) and Select Report Type as Download Revenue Type,

Expected: Should display the message as " No records found"

Actual: No displaying any message/chart as below in the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4701710/e387709e-585b-11e4-95c1-7b0978f5bfce.png)

**Comment by binittapmobi** [comment]
done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/CustomReports

Below is the screenshot
![image](https://cloud.githubusercontent.com/assets/8113291/4717605/ba697ab6-5916-11e4-831b-9f64724fd33c.png)
