### ISSUE TITLE
P1 issue: Carrier is displaying as Uninor in place of Videocon on Page hits logs at wapdemo.tapmobi.in

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#439]
Expected:Carrier should display as Videocon when user hits through Videocon

Tested URL: http://111.93.115.200/xerces/test.aspx

Tested from the System (Browser - user agent)

Tested MSISDN: 918530852562

Tested carrier and circle: Videocon- Gujarat

Below is the page hit log:

![image](https://cloud.githubusercontent.com/assets/8113291/4573880/d485d702-4f96-11e4-9ee5-36b9bc1eae1e.png)

**Comment by soniyatapmobi** [comment]
updated the msc code in payment gateway
