### ISSUE TITLE
P3 issue: Commands field is  displaying in Details pop up on Content Sets page at NewUI platform

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#440]
Expected: Commands field display should be removed from the Details pop-up on Content sets page

Tesed URL: http://p2.tapmobi.in/ContentSet

Precondition: User is on Content-sets page

Note This issue is common across all pages such as "Sites"/"Pages"/"PPD charging"/Pack charging" and so on..
Steps:
1. Click on SetID button 

Actual: Observe the Commands field display in Details pop up as below in the screenshot

![image](https://cloud.githubusercontent.com/assets/8113291/4574750/8bff5d74-4f9f-11e4-9ce5-884d65ae941d.png)

**Comment by binittapmobi** [comment]
done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed.

Tested URL: http://p2.tapmobi.in/ContentSet

Note: This issue has been fixed across all applicable pages.

Below is the screenshot at Content-sets page:

![image](https://cloud.githubusercontent.com/assets/8113291/4625028/cde84c86-536f-11e4-9970-23ef8fa31b8b.png)

**Comment by virupaksh** [comment]
Retested the reported issue and issue is open only on Details pop up on Pages.

Tested URL: http://p2.tapmobi.in/Pages

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/5083718/e84e693a-6f20-11e4-923a-1de73d78b059.png)

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/Pages

![image](https://cloud.githubusercontent.com/assets/8113291/5104923/fab9e0ee-700c-11e4-9dd8-7db52d1011fd.png)
