### ISSUE TITLE
P3 issue: UI alignment of Sites /Date fields is not proper on X axis for different charts/ graphs such as: Top Visited Sites all time and Top Visited Site last 7 days on Dashboard at p2.tapmobi.in

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#442]
Expected: UI alignment across X and Y axis should be consistent throughout.

Tested URL:  http://p2.tapmobi.in/home

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4611162/823604da-52b7-11e4-9991-070675ccf270.png)

**Comment by binittapmobi** [comment]
replaced with bar charts

**Comment by virupaksh** [comment]
Tested URL: http://p2.tapmobi.in/
Retested, Bar charts have been implemented, Need to do some label changes like Site/Date on X axis for Top Visited Site last 7 days and Total Visit last 7 days charts respectively as below in the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4625216/e91f3390-5372-11e4-9bc3-866dd003da01.png)

**Comment by binittapmobi** [comment]
x & y axis proper label added

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: Tested URL: http://p2.tapmobi.in/

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4641191/11db36ec-5433-11e4-8f97-9c3df29f9903.png)
