### ISSUE TITLE
P1 issue:Not able to create/edit Subscription Details at p2.tapmobi.in

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#443]
Tested URL: http://p2.tapmobi.in/SubscriptionCharging/EditDetails?subsChargeId=21

Expected:Should display the message as " Data has been saved successfully" and entered data should be created/updated accordingly

Actual: There is some error message displaying as below in the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4625161/03bdf46c-5372-11e4-82a5-37521fb159b9.png)

**Comment by binittapmobi** [comment]
added service name which is a mandatory field in database

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/SubscriptionCharging/Details?subsChargeId=23

![image](https://cloud.githubusercontent.com/assets/8113291/4640870/21ec1148-542c-11e4-9134-c3223f46dfb1.png)
