### ISSUE TITLE
P1 issue: Start Date and End Date filters functionality not working on View Pack Subscribers page at P2 portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#446]
Tested URL: http://p2.tapmobi.in/Subscribers?

Expected : Start Date and End Date filters functionality should work accordingly.

Note: This issue exist across all browsers (IE/Mozilla Firefox/Google Chrome)

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4640895/d7235c1a-542c-11e4-9ba5-04d5c163cb05.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue  and issue has been fixed, hence closing the same

Tested URL: http://p2.tapmobi.in/Subscribers?grid-column=Id&grid-dir=1

Note: Filters have been removed for Start Date and End Date calender pickers on View Pack Subscribers page.

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4675380/b276c06e-55f8-11e4-95e5-63ee7073925d.png)
