### ISSUE TITLE
P3 issue: Vendor URL text-box and Fetch button on Search And Add Vendor Items page overlapping at various screen resolution on mobile mode for Mozilla firefox at P2 portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#448]
Tested URL: http://p2.tapmobi.in/ContentSet/SearchVendorItems/161

Tested Browser in mobile mode: Mozilla Firefox-33

Precondition: User logged into the P2 portal on Mozilla fire-fox browser.

Steps:
1. Content -->View Content Sets, Click on Edit Items button -->Click on Search And Add Vendor Items  button on Content Set Items page
2. Enter Control Shift M and observe the page

Actual: Vendor URL text box and Fetch buttons overlapping across all resolutions as below in the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4643688/36e18404-5452-11e4-958a-a2f82c36ef9f.png)

**Comment by binittapmobi** [comment]
Deepak - Done
