### ISSUE TITLE
[PG] - Test Billing URL is not working

### ISSUE THREAD

**Issue by SatheeshAnandan** [vinodtapmobi/havok-operations#45]
We have tested the testing billing URL - 
1. Airtel - Not working
2. Aircel - Not working 
3. Idea - Not working 

Attached Screen short for the same.
![airtel_iphone4_02](https://f.cloud.github.com/assets/6543194/2059969/e3ec38b6-8bed-11e3-97a4-9573826650e3.jpg)
![idea_iphone5_03](https://f.cloud.github.com/assets/6543194/2059970/e3f6eaae-8bed-11e3-8dda-00382c175727.jpg)
![idea_samsung_06](https://f.cloud.github.com/assets/6543194/2059971/e3f9caf8-8bed-11e3-84b1-fdb50c2c9122.jpg)
![aircel_nexus_04 mnp uninor to aircel](https://f.cloud.github.com/assets/6543194/2059972/e3fe8f66-8bed-11e3-8d25-98e34c05bc7a.png)
![aircel_note3_05](https://f.cloud.github.com/assets/6543194/2059973/e4030bea-8bed-11e3-9e3c-4bca1590fb96.png)
![airtel_bb_01](https://f.cloud.github.com/assets/6543194/2059974/e40f82a8-8bed-11e3-84a6-5f8a17cf504a.jpg)

TEST LINK given in the mail...
http://111.93.115.200/xercesnode/test.aspx

**Comment by RuchikaTZ** [comment]
However, I received a message from from CLI : AT-AIRINF saying : Thanks for downloading TECHZONE from Airtel. You have been charged Re 1.0

**Comment by soniyatapmobi** [comment]
Hi Satheesh,

Aircel, Airtel, idea and uninor billing, all are working fine.
Please test all the four once again and let us know if you are still facing any prob.
