### ISSUE TITLE
P2 issue: Subscription Message and Unsubscription Message text boxes on Pack Charging Specifications page accepting special characters only at P2 portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#451]
Expected: Should display the message as " Please enter in Correct format", on entering special characters only into Subscription and Unsubscription Message text boxes

Tested URL: http://p2.tapmobi.in/PackCharging/Create

Note: combination of Special characters along with numerics can be accepted, but not only special characters.

Steps:
1. Specifications -->View Pack Specifications -->Create Pack Charging Specification
2. Enter the text as "!@#$@$!" into  Subscription Message and Un-subscription Message text boxes and Click on Create button

Actual: Only special characters are accepted in Subscription Message and Un-subscription text-boxes as  below in the screenshot.

![image](https://cloud.githubusercontent.com/assets/8113291/4660034/801e906e-5513-11e4-8745-6bf36dea9265.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue, issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/PackCharging/Create

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4662822/beb05d68-5535-11e4-9860-da0ed20199a3.png)
