### ISSUE TITLE
P3 issue: PPD charging specifications text colliding with Create New PPD Specification button in PPD Charging Specifications  page at P2 portal on Mozilla firefox

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#452]
Expected: Text should not collide with the button

Tested URL: http://p2.tapmobi.in/PpdCharging

Tested browser: Mozilla Firefox-33

Precondition: Press control Shift M keyboard on PPD Charging Specifications page.

Note: This issue is common across all pages such as: Pack Charging Specifications ,Subscription Charging Specifications and Offer Charging Specifications  page as below in the screenshots:
1. PPD charging Specifications page:
   ![image](https://cloud.githubusercontent.com/assets/8113291/4660844/6433b2ea-551c-11e4-9b22-3c4825da3da3.png)
2. Pack charging Specifications page:
   ![image](https://cloud.githubusercontent.com/assets/8113291/4660855/86c488d4-551c-11e4-82c7-8f7f50ae98e4.png)
3. Subscription Charging Specifications page:
   ![image](https://cloud.githubusercontent.com/assets/8113291/4660868/b223abf4-551c-11e4-9df9-7156081591a0.png)
4. Offer Charging Specifications page:
   ![image](https://cloud.githubusercontent.com/assets/8113291/4660883/de08369a-551c-11e4-9206-643ac06b7515.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Fixed, hence closed
