### ISSUE TITLE
P1 issue: Pack and Subscription charging types displaying in Create/Edit Offer Rules page at P2 portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#453]
Expected: As offer specification is applicable only for PPD, PPD only should display in Charging Type drop-down.

Tested URL: http://p2.tapmobi.in/Offers/CreateRules/29
                     http://p2.tapmobi.in/Offers/EditRules/47

Precondition: User/Admin is logged into the P2 portal

Steps:
1. Specifications -->View Offer Specifications
2. Click on Create New Offer Specification button on Offer Charging Specifications page

Actual: Pack and Subscription values displaying in the Select Charging Type drop-down as below in the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4675601/efa481d0-55fb-11e4-8dbc-c72f54c55fcd.png)

Note: This issue exist on Edit Offer Rules page too.

**Comment by binittapmobi** [comment]
done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same

Tested URL's: http://p2.tapmobi.in/Offers/EditRules/51

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4714400/9f457ae8-58f1-11e4-91f9-27304167a7a0.png)

Below is the screenshot of PPD charging type display:
![image](https://cloud.githubusercontent.com/assets/8113291/4714409/ca62251e-58f1-11e4-8107-967679d00a33.png)
