### ISSUE TITLE
P1 issue:  No item(s) have been selected message is displayed, when user clicks on Enter key  on Apply button in Carrier/Circle/ContentType fileters on Ppd Charging Specification Details  page at p2 porta

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#456]
Expected: When user clicks on Enter key of the keyboard, corresponding filter should be applied and should not display any message such as " No item(s) have been selected" 

Tested URL: http://p2.tapmobi.in/PpdCharging/Details?ppdId=31
Note: This issue is common across all pages where Delete Selected Items button is available and across all browsers

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4788684/ebd8890c-5dbc-11e4-93a0-dc031ceb8cb9.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/PpdCharging/Details?ppdId=45&grid-filter=Carrier__1__airtel

![image](https://cloud.githubusercontent.com/assets/8113291/4975663/89eb7402-6901-11e4-9178-c43fc1f04800.png)
