### ISSUE TITLE
P2 issue: No error message is displayed to the user when there are no items available to display on Ppd Charging Specification Details page at p2 portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#457]
Expected: Should display the message as " There are no items to display "

Tested URL: http://p2.tapmobi.in/PpdCharging/Details?ppdId=31&grid-filter=Hour__5__23

Note: This issue is common across all pages such as Pack Charging Specification Details page, Subscription Charging Specification Details page and Content Set Items page

Steps:
1. Login to the P2 portal
2. Specifications -->View PPD Specifications -->Click on Details button -->Click on ID filter on Ppd Charging Specification Details page -->Enter the value as "5000" and Click on Apply button

Actual: No message is displayed to the user as below in the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4788836/890e89dc-5dbe-11e4-9e44-d018b4dd5176.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed as the message has been added below in the screenshot.

Tested URL: http://p2.tapmobi.in/ContentSet/Items/225

Need to remove Delete Selected Items button and Select ALL checkbox when there are no items available in the page as below
 Note: This is common across all pages where there is no items available in the page

![image](https://cloud.githubusercontent.com/assets/8113291/4896053/f4eee7ce-63f3-11e4-92d5-e8a454901b9a.png)

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed.

Tested URL: http://p2.tapmobi.in/ContentSet/Items/225

Below is the screenshot:

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed. Hence closing the same.

Tested URL: http://p2.tapmobi.in/ContentSet/Items/225

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4992825/77603f9a-69cc-11e4-91af-9f79a71121a1.png)
