### ISSUE TITLE
P1 issue: Cancel button (X) for OfferID is not available at Properties screen for any control at editor for p2 portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#459]
Expected: There should be Cancel button, so that user can click on it to cancel and can add new one.

Actual: There is no cancel button available for OfferID

Note: Cancel button is available for Ppd Charging Id/Pack Charging Id/Subscription Charging Id/Ppd/Pack/Subscription Consent Page Id

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4804583/257fde50-5e6f-11e4-9c38-75f75ab074c8.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/app/gui/editor.html?pageId=475

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4896082/4b826f84-63f4-11e4-8241-3af8cba1f05b.png)
