### ISSUE TITLE
[CG] MNP Billing.

### ISSUE THREAD

**Issue by saurabhtz** [vinodtapmobi/havok-operations#46]
Need to integrated billing for MNP too.
It will be on the basis of IP pooling instead of series.
Have done the same integrated in previous platform.

**Comment by saurabhtz** [comment]
We need to bill on the basis of IMSI and not on the basis of mobile number. So need take IMSI details.

**Comment by vinodtapmobi** [comment]
We ARE using IMSI logic itself. Fallback is given below
1) Detect based on IMSI
2) Detect based on IP
3) Detect based on MSISDN

**Comment by soniyatapmobi** [comment]
Added the functionality of getting the network details from imsi code.
There is table in payment gateway database by name Imsicode which will be filled at the time creating the database for the first time using the seeder function. whenever we get the imsi in the header we will check in the database with matching imsi and get the detail.

If imsi is not there, then we will check with ip.
Same way we have table by name IpDetail in the database, Whenever we get the ip which check in the database and get the details.

Even if ip is no there, then will detect based on mobile series code
