### ISSUE TITLE
P2 issue: Link is not available at Page Count field on Sites page and SiteId field on View Pages to redirect accordingly at p2 portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#460]
Expected: There should be link on Page Count field on Sites page, so that on clicking user will redirect to the corresponding page and similarly on SiteID field on Pages, so that user will redirect to corresponding SiteID.

Tested URL's:
http://p2.tapmobi.in/Sites
http://p2.tapmobi.in/Pages

Note: Link navigation is not available on Items field on Content Sets page and Rules Count field on Offer Charging Specifications page

Below is the screenshot on Sites page:
![image](https://cloud.githubusercontent.com/assets/8113291/4804696/527a3368-5e71-11e4-806a-0ec518b06cda.png)

Below is the screenshot on Pages:
![image](https://cloud.githubusercontent.com/assets/8113291/4804726/c8c14fc0-5e71-11e4-846a-0b830118328c.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and redirection implemented as expected, hence closing the same

Redirection Added form Pages to Sites and Vice- versa as below in the screenshot:

Tested URL's:
http://p2.tapmobi.in/Pages?siteId=100

![image](https://cloud.githubusercontent.com/assets/8113291/4896123/eaf784aa-63f4-11e4-843f-91735da3d6d7.png)

![image](https://cloud.githubusercontent.com/assets/8113291/4896129/f91bdde2-63f4-11e4-82ad-c70ab92ec3ef.png)
