### ISSUE TITLE
P1 issue: This field is required error message at Search and Add Vendor Items page is displaying.

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#468]
Expected: Filter functionality should work as expected

Tested URL: http://p2.tapmobi.in/ContentSet/SearchVendorItems/223

Steps:
1. Login to P2 portal, Content -->View Content Sets --> Click on Items link/Edit Items button
2. Click on Search Vendor Items button and Enter the url as "http://180.179.207.113:8080/Lumataxmlgenerator/?cat=Fashion" in  Vendor URL textbox
3. Click on Fetch button
4. Click on any filter for any of the field on the page
Ex: Title filter  -->Enter the value as any available title for any of the type such as : Equals/Start with/ Ends with/ Contains etc..
5. Click on Apply button in the filter dialog

Actual: This field is required error message throwing just beneath the Vendor URL text-box

Expected: Should filter and display the value based on entered input

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/4974407/a6f4c0cc-68f1-11e4-939d-f895e50493e2.png)

**Comment by binittapmobi** [comment]
Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue is fixed as far as filter functionality is concerned, but Error message still displaying the same.

Tested URL: http://p2.tapmobi.in/ContentSet/SearchVendorItems/229

![image](https://cloud.githubusercontent.com/assets/8113291/5141642/1196aefe-719e-11e4-8d4d-c7e45f87d0ed.png)

**Comment by binittapmobi** [comment]
Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, This field is required error message not displaying and filter functionality is working fine as expected.

Tested URL: http://p2.tapmobi.in/ContentSet/SearchVendorItems/225?grid-filter=Title__2__Get%20glossy%20lips

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/5243473/750f377a-796a-11e4-92d7-b12e4e857e53.png)
![image](https://cloud.githubusercontent.com/assets/8113291/5243511/c62bf3e6-796a-11e4-9f22-d7610e3313b3.png)
