### ISSUE TITLE
P1 issue: Error message stating "The value should be greater than 0" displaying on entering the input as "100000000000" in Duration in minutes and Maximum download limit, ValidityDays field in Create/Edit  Pack/Subscription Details page at P2 portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#469]
Expected: Should accept the entered value and not throw any error message

Tested URL: http://p2.tapmobi.in/PackCharging/EditDetails?packId=67
                     http://p2.tapmobi.in/SubscriptionCharging/EditDetails?subsChargeId=29

Note: Same issue exist for BuyCount, GetCount and Rank field on Create/ Edit Offer Rule page

Below is the screenshot at Create/Edit Offer Rule page:

![image](https://cloud.githubusercontent.com/assets/8113291/4974553/e12ed3e4-68f2-11e4-9579-210884173fad.png)

Below is the screenshot on Pack details page:

![image](https://cloud.githubusercontent.com/assets/8113291/4974579/13a822ee-68f3-11e4-9c4e-6c8ed59d89c3.png)

Note: Same issue exist in Create/Edit Subscription charging specification details page:

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed

Tested URL: http://p2.tapmobi.in/Offers/CreateRules/43

Note: Below Error message can be changed:  "Must be min 1 & max 2147483647 in value

![image](https://cloud.githubusercontent.com/assets/8113291/5065523/b3c674d4-6e47-11e4-909e-cc87ac085208.png)

Note: This error message exist in all integer fields across the portal such as: 
1. BuyCount/GetCount/Rank fields in Create/Edit Offer Rule page
2. Duration in minutes and Maximum download limit fields in Create/Edit Pack Details
3. PricePoint, ValidityDays, Maximum download limit fields in Create/Edit Subscription Details

**Comment by binittapmobi** [comment]
Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/PackCharging/EditDetails?packId=67

Below is the screenshot at Create/Edit pack details:
![image](https://cloud.githubusercontent.com/assets/8113291/5106146/2eece20e-701b-11e4-8139-cb3ed7328075.png)

Note: This issue has been fixed across Subscription and Offer details
