### ISSUE TITLE
[PL] - Report parameters 

### ISSUE THREAD

**Issue by RuchikaTZ** [vinodtapmobi/havok-operations#47]
We would require the below parameters, filter option, export to excel option:

Promotion type (live, circle, 3rd party, etc)
Bill date & time
Page name
page id
ppd/pack
category name
msisdn
circle
user agent
handset model {for OEMs, list would be given} 
content price
charged price
media type
Content name
URL 
Audio label
bill status
APN
Request IP
Billing type {regular, refire, prefire}
IMSI
Referer {the 3rd party website from which the user came}

**Comment by RuchikaTZ** [comment]
++ Failure & Success data.
Page hits. 
Downloads (paid, free, subscription downloads) separately

**Comment by soniyatapmobi** [comment]
All the columns are given as filters for all the reports and for export to excel we have separated issue -78 so closing this one also
