### ISSUE TITLE
P1 issue: Content ID filter functionality for Banner and Badges content types not working in StaticContent page at P2 portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#470]
Expected: Filter functionality should work as expected and should display the results based on entered value/input by the user.

Tested URL: http://p2.tapmobi.in/ContentSet/StaticContent?

Precondition: User is on Static content page

Steps:
1.  Filter by banner as Content Type
2. Click on the ContentID filter for type: Equals and Enter the value as " OOMPH" and Click on Apply button

Actual:  There are no items to display message displaying

Expected: Should display the OOmph banner
1. Badges filter:
   Select the Filter as Badges
2. Select Ends with as Type in ContentID, Enter the value as h , Click on Apply button 

Actual:Displaying the Contents with ContentID such as : touch and touchy

Expected:  Should display the ContentID such as : touch only.

Note:  Badges images for ContentId Touch and Touchy not displaying and Content ID filter for footer is also not working in the below screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4975541/db0cb956-68ff-11e4-93cd-96040a32540c.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed as far filtering issue is concerned

Tested URL: http://p2.tapmobi.in/ContentSet/StaticContent?grid-filter=ContentId__3__de&grid-filter=ContentType__1__Badges

Below is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8113291/5104605/bc48efa6-7009-11e4-810f-662899588c4a.png)

Badges images not displaying as below in the screenshot: 

![image](https://cloud.githubusercontent.com/assets/8113291/5104670/5bf61ea2-700a-11e4-8251-8f47b041ff92.png)

Above images URL also throwing the error as below:

http://cg.tapmobi.in/Static?clientId=LMT&contentId=touch&width=75&height=50&transcode=0&format=GIF

http://cg.tapmobi.in/Error.html?aspxerrorpath=/Static
