### ISSUE TITLE
P1 issue: Visitor/Download/Download Revenue Reports displaying for the wrong End Date in Custom Reports page at P2 portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#471]
Actual: : Reports displaying for the wrong End Date as compared to selected End Date as input

Expected: Reports should display based on selected type and Start and End Date respectively.

Tested URL: http://p2.tapmobi.in/CustomReports
1. Below is the screenshot for Visitor Report: 
   Input:07/11/2014
   Actual:08/11/2014 as below.

![image](https://cloud.githubusercontent.com/assets/8113291/4976209/5fabf292-6907-11e4-8395-90cf5de5fec5.png)
1. Below is the screenshot for Download Report:
   Input: 03/11/2014

Actual:04-Nov-2014

![image](https://cloud.githubusercontent.com/assets/8113291/4976230/922ddcee-6907-11e4-8d7b-bbef59a5376b.png)
1. Below is the screenshot for Download Revenue Report:

Input: 03/11/2014

Actual:04-Nov-2014

![image](https://cloud.githubusercontent.com/assets/8113291/4976255/cf90fbca-6907-11e4-81ae-b9a646f61c0b.png
![image](https://cloud.githubusercontent.com/assets/8113291/4976616/63a9eab6-690c-11e4-8fd2-0de58544421b.png)

Note:  Wrong End Date Logs displaying in the form of table as well as charts in Custom Reports page.

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/CustomReports

Below is the screenshot for Visitor Report:

![image](https://cloud.githubusercontent.com/assets/8113291/5028671/5b80c238-6b64-11e4-85bf-0e036ae5db70.png)

Below is the screenshot for Download Report:
![image](https://cloud.githubusercontent.com/assets/8113291/5028701/b8b20cfa-6b64-11e4-8c8b-890bcb9f47ba.png)

Below is the screenshot for Download Revenue Report:
![Uploading image.png . . .]()
