### ISSUE TITLE
P2 issue: Detected Width field in Page hits report exceeding the page border at P2 portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#472]
Expected: All the fields/columns  should be there within the page border

Tested URL: http://p2.tapmobi.in/PageHits

Note: IP Address field in Page hits can be hidden so that all the remaining fields will be displayed within the page border properly.

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/4988493/e2fff146-698b-11e4-93be-a1d6a245d12d.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue is open.

Tested URL: http://p2.tapmobi.in/PageHits

Note: Device type field can be hidden.

Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/8113291/5028644/f29a025c-6b63-11e4-8422-dc2b0ecce791.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL: http://p2.tapmobi.in/PageHits

Below is the screenshot where all fields displaying properly in a page:
![image](https://cloud.githubusercontent.com/assets/8113291/5065488/0895dd48-6e47-11e4-81a4-370f58b1a0ea.png)
