### ISSUE TITLE
P1 issue: Rules Count field functionality in Offer Rules page is not working at P2 portal

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#474]
Expected: Offer Rules count should be equal to the number of Rules present within it.

Actual: No of Offer Rules count is different than that of Rules Count display

Tested URL: http://p2.tapmobi.in/Offers

Precondition: User/Admin has logged into the portal and is in Offers page.

Steps:
1. Click on Create New Offer specification button on Offer Charging Specifications page
2. Enter the Valid offer name and Click on Save button and Observe the Rules Count value as 0
3. Click on Rules Count and Create Offer Rule and Observe the Rules Count value as 1
4. Repeat the Step:3 and and Observe the Rules Count value as 2
5. Click on Rules Count  and Delete any one of the rule created

Actual: Rules count value displaying as 1

Expected: Rules count value should display as 2

Below is the screenshot for Rules Count display :

![image](https://cloud.githubusercontent.com/assets/8113291/4989727/313c0ab8-69a3-11e4-86dd-97f70fd7b3cc.png)

Below is the screenshot for the no.of rules available for the above offer:
![image](https://cloud.githubusercontent.com/assets/8113291/4989752/ab0f2b40-69a3-11e4-9d39-023150d94d61.png)

**Comment by binittapmobi** [comment]
Deepak -Done

**Comment by virupaksh** [comment]
Retested the reported issue and issue has been fixed, hence closing the same.

Tested URL:  http://p2.tapmobi.in/Offers
                      http://p2.tapmobi.in/Offers/Rules/43

Below is the screenshot at Offer Specifications page:
![image](https://cloud.githubusercontent.com/assets/8113291/5028444/2e385b0e-6b61-11e4-9e0f-3084f36d5728.png)

Below is the screenshot at Offer Rules page as expected:

![image](https://cloud.githubusercontent.com/assets/8113291/5028456/67c6ab28-6b61-11e4-889d-30058f5ee4e3.png)
