### ISSUE TITLE
P2 issue: Redirecting back to main sites page after clicking on Save/Cancel buttons on Edit site for the filtered site.

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#475]
Expected: Should redirect back to the filtered site page

Tested URL: http://p2.tapmobi.in/Sites
                    http://p2.tapmobi.in/Sites/Edit/157

Note: This issue exist across all pages.

Steps:

Sites -->Filter by siteID -->Edit -->Save/Cancel -->Redirecting back to the main sites page

Below is the screenshot for the filtered site:
![image](https://cloud.githubusercontent.com/assets/8113291/5023738/516d5fee-6b24-11e4-9904-9f7fe2d194f9.png)

Below is the screenshot for the issue: Redirecting back to the main sites page:

![image](https://cloud.githubusercontent.com/assets/8113291/5023759/891a24ae-6b24-11e4-93a4-9e65d4f95e81.png)

**Comment by binittapmobi** [comment]
Deepak - Done

**Comment by virupaksh** [comment]
Retested the reported issue, Issue has been fixed on Sites/Pages only. Should be fixed across all the pages at portal.

Below is the screenshot at Sites as expected:
![image](https://cloud.githubusercontent.com/assets/8113291/5066452/6f4c015e-6e59-11e4-8999-605b52c61a7c.png)

Below is the screenshot at Pages as expected:
![image](https://cloud.githubusercontent.com/assets/8113291/5066457/7cf93d9e-6e59-11e4-9cac-032a6563db94.png)

**Comment by binittapmobi** [comment]
Done

**Comment by virupaksh** [comment]
Retested the reported issue for all pages, Its working fine as expected.

Redirection is happening as expected, hence closing the same.
