### ISSUE TITLE
P3 issue: Clear button functionality is not working in Device Details page

### ISSUE THREAD

**Issue by virupaksh** [vinodtapmobi/havok-operations#517]
Tested URL: http://cluboomph.tapmobi.in/Tools/Device

Expected: On clicking Clear button, Clear button should disappear.

Steps:
1. Enter text in the Enter user agent textbox
2. Click on Clear button

Actual: The Entered text is only clearing, Not the Clear button

**Comment by Rakeshtapmobi** [comment]
Issue has been fixed.Need to publish in live.

**Comment by virupaksh** [comment]
Fixed, Hence closed
