### ISSUE TITLE
[PL] - Logs

### ISSUE THREAD

**Issue by RuchikaTZ** [vinodtapmobi/havok-operations#56]
Searching for logs/reports based on MSISDN.

Bulk uploading of numbers (via text file) must be feasible.

**Comment by soniyatapmobi** [comment]
Hi Ruchika,

1) Can you please elaborate which reports and how you want to search it?
2) Do you want to search all reports based on single msisdn ?
3) Do you want so search one particular report like pagehit, download, subscription after bulk uploading the msisdn?

**Comment by RuchikaTZ** [comment]
Pls find my replies inline:

On Tue, Feb 25, 2014 at 8:34 PM, Soniyatapmobi notifications@github.comwrote:

> Hi Ruchika,
> 
> 1) Can you please elaborate which reports and how you want to search it?
> 
> Its searching for logs for a number/or multiple numbers. All parameters -
> circle, amount charged, how did the user arrive at the page (3rd party,
> circle promotion, live) etc.. (basically all the parameters that is there
> in the report needs to be displayed against the msisdn)
> 
> 2) Do you want to search all reports based on single msisdn ?
> 
> All reports means? Need the history of that MSISDN basically.

3) Do you want so search one particular report like pagehit, download,

> subscription after bulk uploading the msisdn?
> 
> All. All details possible. Entire history.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/vinodtapmobi/havok-operations/issues/56#issuecomment-36016192
> .

## 

[image: TechZone] http://www.56060.in/

Ruchika Gupta / Business Development

8056012500/ ruchika@56060.in

Gee Gee Universal, Chetpet, Chennai
http://www.56060.in

**Comment by soniyatapmobi** [comment]
As discussed with you over the call,

1) Search by single msisdn : Every report tab may be pagehits, downloads, subscriptions or pack user will have filter to search data by single msisdn, which is already there in each report tab.

2) Search by bulk uploaded msisdn : 
a) Will add one more separate tab where you can choose which report you want say pagehit, download, subscription or pack user.
b) You will be able to bulk upload only the msisdn using .csv file.
c) Based on the selected report and msisdn uploaded report will be display.
d) You will have an option of the exporting the report to excel.

**Comment by RuchikaTZ** [comment]
Exactly!

On Wed, Feb 26, 2014 at 3:51 PM, Soniyatapmobi notifications@github.comwrote:

> As discussed with you over the call,
> 
> 1) Search by single msisdn : Every report tab may be pagehits, downloads,
> subscriptions or pack user will have filter to search data by single
> msisdn, which is already there in each report tab.
> 
> 2) Search by bulk uploaded msisdn :
> a) Will add one more separate tab where you can choose which report you
> want say pagehit, download, subscription or pack user.
> b) You will be able to bulk upload only the msisdn using .csv file.
> c) Based on the selected report and msisdn uploaded report will be display.
> d) You will have an option of the exporting the report to excel.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/vinodtapmobi/havok-operations/issues/56#issuecomment-36110827
> .

## 

[image: TechZone] http://www.56060.in/

Ruchika Gupta / Business Development

8056012500/ ruchika@56060.in

Gee Gee Universal, Chetpet, Chennai
http://www.56060.in

**Comment by soniyatapmobi** [comment]
Added tab "Search bulk msisdn" in platform with the following functionality :-
1) Where you can choose the report type.
2) Where you can upload .csv file containing only msisdn.
3) Based on the msisdn in the .csv file report will be generated.
4) Addtionally you can export the report to gridview using the job.
