### ISSUE TITLE
[PL] - Searching Content should have filters

### ISSUE THREAD

**Issue by vinodtapmobi** [vinodtapmobi/havok-operations#7]
The client should be able set filters before searching for content to add to Content Sets.

He should be able set following filters:
1. ContentId
2. ClientId
3. Title
4. Music Label
5. Category
6.. SubCategoy
7. Genre
8. Language
9. Album
10. Cast
11. Music Director
12. Singer
11. Production House
12. Keyword

**Comment by vinodtapmobi** [comment]
Modify existing search api to accomodate filters. where each filter will have column name and value. so request object

``` c#
public class Request
{
         Dictionary <string,string> Filters {get;set;}
         int Page {get;set;}
         int PageSize {get;set;}
} 
```

**Comment by soniyatapmobi** [comment]
Tested the filter with single, multiple values and is working fine
