### ISSUE TITLE
[PL] Streaming.

### ISSUE THREAD

**Issue by saurabhtz** [vinodtapmobi/havok-operations#71]
Streaming option Available for User user can select either download or stream.

Steaming option available for the designer that he can select either only streaming will be available for the user or both options streaming & download Available.

Capture of streaming time:- time to be captured for how much time user has watched the  video.

Start from where the user has left the video.

**Comment by vinodtapmobi** [comment]
On hold. We will do the download only option first.

**Comment by saurabhtz** [comment]
Sir Streaming is the basic feature which every client would requires we need to have it  in the first phase itself . Yes can hold the other feature of streaming eg Time capturing of streamed file n all. 

(This is among the one of the requirements of Lumata which will be closed soon.)

**Comment by vinodtapmobi** [comment]
I think what you are talking about is to play the file after clicking instead of giving the file for download. 

Implementation:
We will just change Content-Disposition header based on the configuration.

Songs and Video block will have property "Provisioning Type" : "Download" or "Play"
