### ISSUE TITLE
[PL] Single login at a time.

### ISSUE THREAD

**Issue by saurabhtz** [vinodtapmobi/havok-operations#72]
with same user name & password only a single user can work on it .

No simultaneous user with same username & Password.

**Comment by soniyatapmobi** [comment]
1) http://geekswithblogs.net/Frez/archive/2010/05/17/preventing-a-user-from-having-multiple-concurrent-sessions.aspx
2) http://www.nullskull.com/articles/20030416.asp
3) http://www.nullskull.com/articles/20030418.asp
