### ISSUE TITLE
[CG] Content Approval

### ISSUE THREAD

**Issue by saurabhtz** [vinodtapmobi/havok-operations#73]
Content Approval:- Content will be live only after the admin has given approval for the content.  Unapproved content will get removed from the portal.

Automatic trigger to admin if any CP uploads the content.

Automatic trigger along with issue if the content is not uploaded to CP.

**Comment by aravind56060** [comment]
Content Approval :-
Client Admin can approve content in http://cgp.tapmobi.in/App/Admin/ApproveMetadata.aspx.
By default it will display last 200 content uploaded to platform. 
1)Client Admin can Approve or UnApprove either one by one or select All metadata and approve. 
2)Client Admin can filter metadata based on the following fields
    \*   ContentId
    \*   ClientId
    \*   Title
    \*   ContentType
    \*   MusicLabel
    \*   CreatedDate
    \*   Category
    \*   SubCategory
    \*   Language
    \*   Album
    \*   ProductionHouse
3) Only Approved Content will be used for search in CG API
4) Content which are updated will update in our system after half an hour only. 

Automatic trigger will be sent to all client admins whenever new content has been uploaded.
Automatic trigger will be sent to all client users whenever an error occurred while importing content into platform. All the errors will be accumulated and send at once.

**Comment by aravind56060** [comment]
Please find the mailer for Admin and Sub-Users

Mail to Sub-User:-
Mail Subject:- Content Upload Status.
Mail Body:-

Dear  User,
This is automated content upload status message.
Below is the status of uploaded content.

{No of Files} Successfully Uploaded.
{No of Files} Fail to upload.

Please rectify the error file code and upload the content again.

Thanks,
PlatformAdmin@Tapmobi.in

Mail to Admin.
Mail Subject:- Content Approval. 
Mail Body:

Dear Admin,
This is automated content approval mail.

{No of Files}/ { Time & Date of upload} is waiting for your approval 

Please visit cgp.tapmobi.in  to approve the same.

Thanks,
PlatformAdmin@Tapmobi.in
