### ISSUE TITLE
Update DeviceDetails (Implement all WURFL capabilities)

### ISSUE THREAD

**Issue by aravind56060** [vinodtapmobi/havok-operations#77]

**Comment by soniyatapmobi** [comment]
1) All the property values are added except PreferredRenderingType and SupportsJ2Me.
2) As there is no separate parameter to check the j2me support for the device. It is there with other property.
3) There is no parameter like PreferredRendering in wurfl dll.

**Comment by soniyatapmobi** [comment]
1) Updated the devicedetaildto with the new property of device detail in platform node.
