### ISSUE TITLE
[PL] Create packs feature

### ISSUE THREAD

**Issue by vinodtapmobi** [vinodtapmobi/havok-operations#85]
- Pack template - If we click on the subscribe link then only we should subscribe user. Even if he clicks any of the content in page, we should highlight click to subscribe link.
- Pack with subscription - If user clicks on any content or on the link he will get subscribed. and reload the same page.
- Pack with PPD download- If user clicks on any content directly PPD billing and download will happen. But user will not be subscribed to the pack. If user is subscribed to the pack All content should be free download.
- Pack with download limit - Subscriber can download only the defined number of contents from the page.

**Comment by vinodtapmobi** [comment]
Pack template - Client should have a option to disable or make block content (only for pack) non-interactive if the user is not subscribed.

Pack with subscription - This is what PackControl does

Pack with PPD download - Blocks marked as PPD will remain PPD.

Pack with download limit can be done.

**Comment by vinodtapmobi** [comment]
Content Block Rendering for Packs
1. If user is subscribed, he should be able to click on a content and download it. If MaxDownload count is reached, mark status as INACTIVE and continue the download.
2. If user is not subscribed there can be three options
     a) Content Items are disabled/Not clickable
     b) Content items are clickable but it will subscribe the user for the pack. if successful billing, the user if bought back to the original page or else display error (Need to get clarity on this).
     c) Content items are clickable but it is given as PPD. 

These options are given at BLOCK level as drop-down. 
Pack Options: 
1. Disable user interaction
2. Subscribe to pack
3. Provide PPD download

## Implemention

1) How to check if user is subscribed : The status should be ACTIVE and current datetime should be within validity.
2) Urls for content items are consistent for ALL 3 pack options. i.e content items always point to download handler.
3) How to provide PPD download for Pack content :  (if block charging type == "PACK" AND if user is not subscribed AND Pack Option is set to "Provide PPD Download") GOTO Ppd download.
4) Pack item downloads SHOULD also be logged in Downloads table.

**Comment by aravind56060** [comment]
Update the pack status to inactive when
                 1) Pack is not unlimited
                 2) Content is not already downloaded
                 3) If no of unique downloads is equal to pack's Max download limit - 1
And  Provide Download in following cases
                 1) If user already downloaded the content.
                 2) If MaxDownloadContent is 0 (ie) Unlimited content download.
                 3) if no of unique downloads is less than pack Max download limit
