### ISSUE TITLE
[PL] - Create song content block

### ISSUE THREAD

**Issue by vinodtapmobi** [vinodtapmobi/havok-operations#86]

**Comment by soniyatapmobi** [comment]
1) Animation grid control are working and downloading.
2) Wallpaper grid control are working and downloading.
3) Video gird control are working and downloading.

For songs control, there should be an option of user clicking on the content when preview is not available. Need to discuss on this point.

@saurabhtz  Please test the wallpaper, animation and video control and try downloading the same in the mobile with 0 price point.

**Comment by soniyatapmobi** [comment]
Linear theme is now working for animation, wallpaper, video and song control with download.

@saurabhtz  Please test the same with the live url in mobile.

**Comment by saurabhtz** [comment]
Hi Soniya.
Below are the features which are not yet working.

1.Horizontal align
2. Vertical Align
3. Boarder style
4. Margin & Padding
5. Float clear & Display please explain the functioning of the features.
