### ISSUE TITLE
[CG] Create an interface for managing client permission in cg portal

### ISSUE THREAD

**Issue by soniyatapmobi** [vinodtapmobi/havok-operations#94]
1) We need to have one more page say AddClientPermission.aspx under Client admin folder App/Admin/AddClientPermission.aspx so it will be accessible by only client admin or platform admin.
2) GUI will have following control:-
     a) TextBox for entering client id to which he want to give permission, validation has to be done for this 
         like proper client id format and client id entered is exiting client id or not.
     b) Drop down for choosing basic content type say dynamic, static  or both.
     c) Drop down for choosing permission type. Following will be the possible permission type :-1:  
         1) Full access - Access to all the content
         2) Content Type - Access to particular content type say only to wallpaper.
         3) Language - Access to english, hindi content.
         4) Music label - Access to particular music label content say for sony international content.
         5) Album
     d) Text box for entering permission value with validation
     e) Submit button - on submit permission details will be added to the clientpermission table.

**Comment by soniyatapmobi** [comment]
1) Added a page AddClientPermission.aspx where client can give access of his content to already existing client.
2) Following are the permission type 
     a) Album
     b) Content Type
     c) Dynamic
     d) Full access
     e) Language
     f) MusicLabel
     g) Static 
@saurabhtz  Please suggest if you want any other permission type too.
3) Added a page clientpermissions.aspx for displaying the existing client permission.

**Comment by soniyatapmobi** [comment]
1) For permission type full access, dynamic and static permission value will be null.
2) For other permission type you need to enter the permission value too.

**Comment by saurabhtz** [comment]
Unable to login to filezilla through client created using cgp.tapmobi.in

**Comment by saurabhtz** [comment]
Hi Soniya,

As discussed over call below are the inputs.

Admin will be Tapmobi.

Further clients will be for eg :- Karbonn , Zen & Lumata.

when i configure a client ID that client should have access to upload content through file zilla.

That client should have access to CPG.tapmobi.in through his created ID.
and should be able to create sub users.
Admin will be that Cliend id that is karbonn or Zen which should have rites to allow content access uploaded by him or Sub clients.

No need to  have admin options for sub clients as the admin will be the client created by master Admin(Tapmobi).

**Comment by soniyatapmobi** [comment]
@saurabhtz  Please create a new issue for automatically creating file zilla user as soon as the new client is added to the content gateway.
closing this issue

**Comment by vinodtapmobi** [comment]
Guys,

There will be no concept of ADMIN. even techzone or tapmobi are clients.
karbonn, zen are also clients.

ANY Client can give access to their content TO another client. if techzone
wants to give access to their content to karbonn and zen, they can.

On Thu, Apr 3, 2014 at 7:29 PM, Soniyatapmobi notifications@github.comwrote:

> @saurabhtz https://github.com/saurabhtz Please create a new issue for
> automatically creating file zilla user as soon as the new client is added
> to the content gateway.
> closing this issue
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/vinodtapmobi/havok-operations/issues/94#issuecomment-39453920
> .

## 

_Vinod Kumar Y.S_
tel: +91-7760049427
