### ISSUE TITLE
[CG]- Client ID created on CG have access to upload content.

### ISSUE THREAD

**Issue by saurabhtz** [vinodtapmobi/havok-operations#99]
A Client & Subclient created must have rites to upload content on the CG portal through File zilla.

Needs to be created access on FTP once user is created on CG.

**Comment by vinodtapmobi** [comment]
FTP upload can be done only using one username and password.

FTP access will be created by operations team manually and will be provided.

**Comment by saurabhtz** [comment]
Make it an automated work .

When ever an ID will be created a mail will be raised to operation team for creating an access to FTP .
an a mail will be generated to client created that you will have access to FTP in next XYZ Hrs.
